# Generated by Django 4.0.3 on 2022-03-09 18:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='eduprogram',
            old_name='numcode',
            new_name='programcode',
        ),
        migrations.RemoveField(
            model_name='dicteduplantype',
            name='edutype',
        ),
        migrations.RemoveField(
            model_name='discipteacher',
            name='subject',
        ),
        migrations.RemoveField(
            model_name='eduprogram',
            name='edulevel',
        ),
        migrations.AddField(
            model_name='dictblocktype',
            name='isoop',
            field=models.BooleanField(default=True, verbose_name='ИзООП'),
        ),
        migrations.AddField(
            model_name='dicteduqualifi',
            name='edutype',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='edu_type', to='schedule.dictedulvl', verbose_name='Уровень образования (НПО, СПО, ВПО)'),
        ),
        migrations.AddField(
            model_name='dictobjtype',
            name='iscomlpex',
            field=models.BooleanField(default=True, verbose_name='Составляющий'),
        ),
        migrations.AddField(
            model_name='dictprogramlvl',
            name='edulvl',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='educationlvl', to='schedule.dictedulvl', verbose_name='Уровень образования (НПО, СПО, ВПО)'),
        ),
        migrations.AddField(
            model_name='discipteacher',
            name='teacher',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='teachsubj', to='schedule.depteacher', verbose_name='Преподаватель'),
        ),
        migrations.AddField(
            model_name='eduprogram',
            name='edulvl',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='edu_lvl', to='schedule.dictedulvl', verbose_name='Уровень образования'),
        ),
        migrations.AddField(
            model_name='plangraf',
            name='rowcode',
            field=models.IntegerField(default=0, verbose_name='Код строки файла'),
        ),
        migrations.AddField(
            model_name='planhours',
            name='rowcode',
            field=models.IntegerField(default=0, verbose_name='Код строки файла'),
        ),
        migrations.AlterField(
            model_name='dictedubase',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='childedubase', to='schedule.dictedubase', verbose_name='Родитель'),
        ),
        migrations.AlterField(
            model_name='dicti',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='schedule.dicti', verbose_name='Родитель'),
        ),
        migrations.AlterField(
            model_name='plangraf',
            name='activitykindcode',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='КодВидаДеятельности GosInsp'),
        ),
        migrations.AlterField(
            model_name='planrow',
            name='objkind',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rowobjkind', to='schedule.dictobjkind', verbose_name='Вид Объекта'),
        ),
        migrations.AlterField(
            model_name='planrow',
            name='objtype',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rowobjtype', to='schedule.dictobjtype', verbose_name='Тип объекта'),
        ),
        migrations.CreateModel(
            name='DictActKind',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(blank=True, max_length=50, null=True, verbose_name='Символьный код')),
                ('numcode', models.SmallIntegerField(blank=True, null=True, verbose_name='Числовой код')),
                ('shortname', models.CharField(blank=True, max_length=50, null=True, verbose_name='Краткое наименование')),
                ('fullname', models.CharField(max_length=4000, verbose_name='Полное наименование')),
                ('abbrname', models.CharField(blank=True, max_length=50, null=True, verbose_name='Аббревиатура')),
                ('constname', models.CharField(blank=True, max_length=100, null=True, verbose_name='Константа')),
                ('prefix', models.CharField(blank=True, max_length=50, null=True, verbose_name='Префикс')),
                ('active', models.BooleanField(default=True, verbose_name='Актуальность')),
                ('extid', models.CharField(blank=True, max_length=100, null=True, verbose_name='код Gosinsp')),
                ('acttype', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='act_type', to='schedule.dictworktype', verbose_name='Вид деятельности')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='schedule.dictactkind', verbose_name='Родитель')),
            ],
            options={
                'verbose_name': 'Справочник Вид деятельности',
                'verbose_name_plural': 'Справочник Виды деятельности',
            },
        ),
        migrations.AlterField(
            model_name='plangraf',
            name='activitykind',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activ_kind', to='schedule.dictactkind', verbose_name='Вид деятельности'),
        ),
    ]
