# Generated by Django 4.0.3 on 2022-05-01 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0002_rename_numcode_eduprogram_programcode_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='studyfile',
            name='file',
            field=models.FileField(null=True, upload_to='uploads'),
        ),
    ]
