# Generated by Django 4.0.3 on 2022-05-01 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0003_studyfile_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studyfile',
            name='file',
            field=models.FileField(null=True, upload_to='uploads', verbose_name='Файл'),
        ),
        migrations.AlterField(
            model_name='studyfile',
            name='filetext',
            field=models.TextField(blank=True, null=True, verbose_name='Текст файла'),
        ),
        migrations.AlterField(
            model_name='studyfile',
            name='title',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Название файла'),
        ),
    ]
