# Generated by Django 4.0.3 on 2022-05-02 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0006_alter_studyfile_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studyfile',
            name='file',
            field=models.FileField(null=True, upload_to='', verbose_name='Файл'),
        ),
    ]
