# Generated by Django 4.0.3 on 2022-05-03 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0007_alter_studyfile_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dicteduqualifi',
            name='edulevelplan',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Вид плана'),
        ),
        migrations.DeleteModel(
            name='DictEduPlanType',
        ),
    ]
