# Generated by Django 4.0.3 on 2022-05-07 11:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0011_alter_planprog_department'),
    ]

    operations = [
        migrations.AlterField(
            model_name='planprog',
            name='eduprog',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='studyprog', to='schedule.eduprogram', verbose_name='Образовательная программа'),
        ),
        migrations.AlterField(
            model_name='planprog',
            name='period',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='period', to='schedule.studyperiod', verbose_name='УчебныйГод'),
        ),
    ]
