# Generated by Django 4.0.3 on 2022-05-07 11:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0012_alter_planprog_eduprog_alter_planprog_period'),
    ]

    operations = [
        migrations.AlterField(
            model_name='planhours',
            name='activityclass',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='worktype', to='schedule.dictworktype', verbose_name='Тип объекта'),
        ),
        migrations.AlterField(
            model_name='planhours',
            name='activitysubclass',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='workkind', to='schedule.dictworkkind', verbose_name='Вид работы по справочнику КодВидаРаботы'),
        ),
        migrations.AlterField(
            model_name='planhours',
            name='discipline',
            field=models.ForeignKey(default=0, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='phdiscip', to='schedule.discipline', verbose_name='Дисциплина'),
        ),
        migrations.AlterField(
            model_name='planhours',
            name='hoursclass',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='hoursclass', to='schedule.dicthourstype', verbose_name='Тип Часов'),
        ),
        migrations.AlterField(
            model_name='planhours',
            name='plan',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='hoursplan', to='schedule.planprog', verbose_name='План за определенный год'),
        ),
        migrations.AlterField(
            model_name='planrow',
            name='discipline',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rowdiscip', to='schedule.discipline', verbose_name='дисциплина'),
        ),
        migrations.AlterField(
            model_name='planrow',
            name='objkind',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rowobjkind', to='schedule.dictobjkind', verbose_name='Вид Объекта'),
        ),
        migrations.AlterField(
            model_name='planrow',
            name='objtype',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rowobjtype', to='schedule.dictobjtype', verbose_name='Тип объекта'),
        ),
        migrations.AlterField(
            model_name='planrow',
            name='plan',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rowplan', to='schedule.planprog', verbose_name='План за определенный год'),
        ),
    ]
