# Generated by Django 4.0.3 on 2022-05-07 11:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0013_alter_planhours_activityclass_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plangraf',
            name='plan',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='grafplan', to='schedule.planprog', verbose_name='План за определенный год'),
        ),
    ]
